version: '3'

services:
    api-flask:
      image: ${DOCKER_IMAGE}
      container_name: ${CONTAINER_NAME}
      build: 
        context: . 
        dockerfile: Dockerfile
      ports: 
        - '5000:5000'
      env_file:
        - .env