// 1. Buildar a imagem 
// 2. Fazer o push da imagem para o Docker Hub
// 3. Rodar a imagem na maquina

pipeline {
    agent {
        label 'pietro'
    }

    environment {
        DOCKER_IMAGE = "${DOCKER_REGISTRY}"
    }

    stages {
        stage('Image Build') {
            steps {
                echo 'docker_registry: $DOCKER_REGISTRY'
            }
        }
        
    }
}