// 1. Buildar a imagem 
// 2. Fazer o push da imagem para o Docker Hub
// 3. Rodar a imagem na maquina

pipeline {
    agent {
        label 'pietro'
    }

    environment {
        DOCKER_IMAGE = "${DOCKER_REGISTRY}/api-flask:${BUILD_NUMBER}"
    }

    stages {
        stage('Image Build') {
            steps {
                echo "nome da imagem: $DOCKER_IMAGE"
                sh "docker build -t $DOCKER_IMAGE --no-cache -f Dockerfile ."
            }
        }

        stage('Image Push') {
            steps {
                echo "fazendo o push da imagem: $DOCKER_IMAGE"
                //sh "docker tag api-flask:$BUILD_NUMBER $DOCKER_IMAGE"
                //sh "docker push $DOCKER_IMAGE"
            
            }
        }

        stage('Image Run') {
            steps {
                sh "touch .env"
                echo "rodando a imagem: $DOCKER_IMAGE"
                echo "DOCKER_IMAGE=$DOCKER_IMAGE >> .env"
                echo "CONTAINER_NAME=api-flask-prod >> .env"

                //sh docker image pull ${params.DockerImage}
                sh "docker compose -f docker-compose-ci.yaml up -d"
            
            }
        }
        

    }
}